### ISSUE TITLE
Mistakes in「算術第三」and「行列第六」

### ISSUE THREAD

**Issue by zetaraku** [wenyan-lang/book#12]
There seem to be some mistakes in「算術第三」and「行列第六」:

> 「大數之類。一。十。**十一曰百**。十百曰千。」

「十一曰百」should be「十十曰百」

> 「萬萬曰億。萬億曰兆。萬京曰陔。」

Missing「萬兆曰京。」

> 戴九履一。左三右七。二四為肩。六八為足。

Missing 「五居中央。」(maybe)

**Comment by LingDong-** [comment]
Hi, thanks a lot for pointing out the mistakes!

The ones in 算術第三 were already fixed in the markdown version a while ago, I'll regenerate the PDF soon:

https://github.com/wenyan-lang/book/commit/49c048897d9d5adfcb2cb5aa0d05c00436310a2f#diff-373dee6bcc35b7793bbafc7c83fdce7f

And I fixed the one in 行列第六 9c715acfcc6c631f1128c2f55ccd938afe50c767 just now

Thanks!

**Comment by zetaraku** [comment]
I found another mistake in 「言語第七」

> 加「**甲**」於「「夫五常者」」。加其以「「是也」」書之。

Here「甲」should be「五常」

**Comment by LingDong-** [comment]
@zetaraku, thanks for spotting the mistake (and sorry for the late reply), now fixed in 5b7c7a2d812b23fab0755d5dfdc9f34f9750f301

**Comment by LingDong-** [comment]
_

**Comment by 747** [comment]
https://github.com/wenyan-lang/book/blob/9c715acfcc6c631f1128c2f55ccd938afe50c767/06%20%E8%A1%8C%E5%88%97%E7%AC%AC%E5%85%AD.md#L46

I stumbled at this line. Could it be that this `既之其長` actually is `既知其長`? Any suggestion would be appreciated.

**Comment by LingDong-** [comment]
Hi @747, thanks for spotting the typo! now fixed: 8a182e3f2999ea4356a2800e97c246c1ac75eb37
